// Auth
export const SIGN_IN_INITIATED = 'SIGN_IN_INITIATED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGNING_IN_FAILED = 'SIGNING_IN_FAILED';

// Navigator
export const CONNECTED_WITH_SERVER = 'CONNECTED_WITH_SERVER';
export const COULD_NOT_CONNECT_TO_SERVER = 'COULD_NOT_CONNECT_TO_SERVER';

// Student
export const STUDENT_EXTRA_DATA_LOADED = 'STUDENT_EXTRA_DATA_LOADED';
